export const GET_NEWSLETTERS = 'GET_NEWSLETTERS';
export const ADD_NEWSLETTER = 'ADD_NEWSLETTER';
export const ADD_MAIL_USER= 'ADD_MAIL_USER';
export const SEND_MAIL_USER= 'SEND_MAIL_USER';
export const GET_ALL_NEWSLETTER_TYPE= 'GET_ALL_NEWSLETTER_TYPE';
export const GET_ONE_NEWSLETTER= 'GET_ONE_NEWSLETTER';
export const GET_ALL_SUSCRIBED= 'GET_ALL_SUSCRIBED';
export const GET_STATISTICS= 'GET_STATISTICS';





